Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.6
Style/StringLiterals:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Layout/LineLength:
  Max: 100
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Style/IfUnlessModifier:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
